"use client";

import { useMemo } from "react";
import type { Theme, Lang } from "../types";
import { tokens } from "../theme/tokens";
import { brandGradients } from "../theme/gradients";

const FONT_HEADING = "'Cormorant Garamond', serif";
const FONT_BODY = "'Heebo', sans-serif";
const FONT_MONO = "'Inter', sans-serif";

export function useStyles(theme: Theme, lang: Lang, animateIn: boolean = true) {
  const c = tokens[theme];
  const isRTL = lang === "he";
  const gradients = brandGradients[theme];

  return useMemo(() => {
    // Category labels for translations
    const categoryLabels: Record<string, Record<string, string>> = {
      "anti-age": { he: "אנטי-אייג׳", ru: "Anti-age" },
      "hydration": { he: "לחות", ru: "Увлажнение" },
      "cleansing": { he: "ניקוי", ru: "Очищение" },
    };

    return {
      // ─────────────────────────────────────────────────
      // APP SHELL
      // ─────────────────────────────────────────────────
      app: {
        fontFamily: `${FONT_HEADING}, ${FONT_BODY}`,
        maxWidth: 430,
        margin: "0 auto",
        height: "100vh",
        backgroundColor: c.bg,
        color: c.text,
        direction: isRTL ? "rtl" : "ltr",
        position: "relative" as const,
        overflow: "hidden",
        transition: "background-color 0.6s cubic-bezier(0.4, 0, 0.2, 1), color 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
      },
      header: {
        position: "fixed" as const,
        top: 0,
        left: "50%",
        transform: "translateX(-50%)",
        width: "100%",
        maxWidth: 430,
        height: 64,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "0 20px",
        backgroundColor: c.glass,
        backdropFilter: "blur(24px) saturate(180%)",
        WebkitBackdropFilter: "blur(24px) saturate(180%)",
        borderBottom: `1px solid ${c.border}`,
        zIndex: 100,
        transition: "background-color 0.6s ease",
      },
      logo: {
        width: 42,
        height: 42,
        borderRadius: 21,
        border: `2px solid ${c.accent}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
      },
      logoImage: {
        width: "100%",
        height: "100%",
        objectFit: "cover" as const,
      },
      logoPlaceholder: {
        fontFamily: FONT_HEADING,
        fontSize: 22,
        fontWeight: 500,
        color: c.accent,
        lineHeight: 1,
      },
      headerActions: {
        display: "flex",
        alignItems: "center",
        gap: 8,
      },
      iconBtn: {
        width: 44,
        height: 44,
        borderRadius: 22,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "transparent",
        border: "none",
        cursor: "pointer",
        color: c.text,
        transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
      },
      langToggle: {
        fontSize: 13,
        fontWeight: 600,
        padding: "8px 14px",
        borderRadius: 20,
        backgroundColor: c.bgSecondary,
        border: `1px solid ${c.border}`,
        cursor: "pointer",
        color: c.text,
        fontFamily: FONT_MONO,
        letterSpacing: "0.02em",
        transition: "all 0.3s ease",
      },
      cartBadge: {
        position: "absolute" as const,
        top: 6,
        [isRTL ? "left" : "right"]: 6,
        width: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: c.accent,
        color: "#FFF",
        fontSize: 10,
        fontWeight: 700,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: FONT_MONO,
        boxShadow: `0 2px 8px ${c.accent}40`,
      },
      main: {
        height: "100vh",
        overflowY: "auto" as const,
        paddingTop: 64,
        paddingBottom: 100,
      },
      nav: {
        position: "fixed" as const,
        bottom: 20,
        left: "50%",
        transform: "translateX(-50%)",
        display: "flex",
        alignItems: "center",
        gap: 4,
        padding: "8px 12px",
        backgroundColor: theme === "light" ? "rgba(255, 255, 255, 0.96)" : "rgba(31, 28, 25, 0.96)",
        backdropFilter: "blur(24px) saturate(180%)",
        WebkitBackdropFilter: "blur(24px) saturate(180%)",
        borderRadius: 20,
        border: `1px solid ${c.borderStrong}`,
        boxShadow: c.shadowDeep,
        zIndex: 100,
      },
      navItem: (active: boolean) => ({
        height: 54,
        borderRadius: 16,
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
        padding: "6px 12px",
        backgroundColor: active ? c.accent : "transparent",
        border: "none",
        opacity: active ? 1 : 0.85,
        cursor: "pointer",
        color: active ? "#FFF" : c.textSecondary,
        transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
        fontFamily: FONT_BODY,
        fontSize: 10,
        fontWeight: 500,
        boxShadow: active ? `0 4px 16px ${c.accent}40` : "none",
        minWidth: 56,
      }),

      // ─────────────────────────────────────────────────
      // SECTION COMMON
      // ─────────────────────────────────────────────────
      section: {
        padding: "28px 20px",
        opacity: animateIn ? 1 : 0,
        transform: animateIn ? "translateY(0)" : "translateY(20px)",
        transition: "opacity 0.6s cubic-bezier(0.4, 0, 0.2, 1), transform 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
        position: "relative" as const,
        zIndex: 1,
        backgroundColor: c.bg,
      },
      sectionTitle: {
        fontSize: 22,
        fontWeight: 500,
        fontFamily: FONT_HEADING,
        marginBottom: 20,
        letterSpacing: "-0.02em",
      },

      // ─────────────────────────────────────────────────
      // HERO - CATALOG
      // ─────────────────────────────────────────────────
      hero: {
        position: "relative" as const,
        height: 320,
        overflow: "hidden",
        marginBottom: 0,
        zIndex: 0,
      },
      heroImage: {
        position: "absolute" as const,
        inset: 0,
        width: "100%",
        height: "100%",
        objectFit: "cover" as const,
        filter: "brightness(0.7)",
      },
      heroGradientOverlay: {
        position: "absolute" as const,
        inset: 0,
        background: `linear-gradient(180deg, transparent 0%, transparent 50%, ${c.bg} 100%)`,
        zIndex: 1,
      },
      heroMesh: {
        position: "absolute" as const,
        inset: 0,
        background: `radial-gradient(ellipse at 50% 30%, ${c.accent}25 0%, transparent 50%),
                     radial-gradient(ellipse at 80% 80%, ${c.accentLight}15 0%, transparent 40%)`,
        zIndex: 2,
      },
      heroBokeh: {
        position: "absolute" as const,
        borderRadius: "50%",
        filter: "blur(40px)",
        animation: "bokehFloat 8s ease-in-out infinite",
        zIndex: 3,
      },
      heroNoise: {
        position: "absolute" as const,
        inset: 0,
        backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")`,
        opacity: 0.03,
        zIndex: 4,
      },
      heroContent: {
        position: "absolute" as const,
        bottom: 60,
        left: 0,
        right: 0,
        textAlign: "center" as const,
        zIndex: 5,
        padding: "0 20px",
      },
      heroTitle: {
        fontSize: 48,
        fontWeight: 400,
        fontFamily: FONT_HEADING,
        letterSpacing: "-0.03em",
        marginBottom: 12,
        color: c.text,
        textShadow: theme === "light" ? "none" : "0 2px 20px rgba(0,0,0,0.5)",
      },
      heroSubtitle: {
        fontSize: 15,
        color: c.textSecondary,
        fontFamily: FONT_BODY,
        fontWeight: 400,
        letterSpacing: "0.02em",
      },
      sparkleIcon: {
        display: "inline-flex",
        animation: "sparkle 2s ease-in-out infinite",
      },

      // ─────────────────────────────────────────────────
      // FILTERS
      // ─────────────────────────────────────────────────
      brandRow: {
        display: "flex",
        gap: 10,
        overflowX: "auto" as const,
        paddingBottom: 8,
        marginBottom: 4,
        scrollbarWidth: "none" as const,
        msOverflowStyle: "none" as const,
      },
      brandPill: (active: boolean) => ({
        padding: "12px 20px",
        borderRadius: 24,
        fontSize: 13,
        fontWeight: 500,
        fontFamily: FONT_BODY,
        backgroundColor: active ? c.accent : c.bgSecondary,
        color: active ? "#FFF" : c.text,
        border: `1px solid ${active ? c.accent : c.border}`,
        cursor: "pointer",
        whiteSpace: "nowrap" as const,
        transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        boxShadow: active ? `0 4px 16px ${c.accent}30` : "none",
      }),
      categoryRow: {
        display: "flex",
        gap: 8,
        overflowX: "auto" as const,
        paddingBottom: 4,
        scrollbarWidth: "none" as const,
        msOverflowStyle: "none" as const,
      },
      categoryPill: (active: boolean, disabled: boolean) => ({
        padding: "10px 16px",
        borderRadius: 20,
        fontSize: 12,
        fontWeight: 500,
        fontFamily: FONT_BODY,
        backgroundColor: active ? c.accentLight : c.bgTertiary,
        color: active ? c.accentDark : disabled ? c.textMuted : c.textSecondary,
        border: "none",
        cursor: disabled ? "not-allowed" : "pointer",
        whiteSpace: "nowrap" as const,
        transition: "all 0.3s ease",
        opacity: disabled ? 0.5 : 1,
      }),

      // ─────────────────────────────────────────────────
      // QUOTE BLOCK
      // ─────────────────────────────────────────────────
      quoteBlock: {
        position: "relative" as const,
        backgroundColor: c.cardSolid,
        borderRadius: 24,
        padding: 28,
        marginBottom: 28,
        boxShadow: c.shadow,
        border: `1px solid ${c.border}`,
        overflow: "hidden",
      },
      quote: {
        fontSize: 17,
        fontStyle: "italic",
        fontFamily: FONT_HEADING,
        lineHeight: 1.6,
        color: c.text,
        marginBottom: 12,
      },
      quoteAuthor: {
        fontSize: 13,
        color: c.textMuted,
        fontFamily: FONT_BODY,
        fontWeight: 500,
      },

      // ─────────────────────────────────────────────────
      // BENTO GRID - PRODUCTS
      // ─────────────────────────────────────────────────
      bentoGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(2, 1fr)",
        gap: 16,
      },
      productCard: (isLarge: boolean, index: number) => ({
        gridColumn: isLarge ? "span 2" : "span 1",
        backgroundColor: c.cardSolid,
        borderRadius: 24,
        overflow: "hidden",
        boxShadow: c.shadow,
        cursor: "pointer",
        transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
        border: `1px solid ${c.border}`,
        animation: `fadeIn 0.6s ease ${index * 0.1}s both`,
      }),
      productImage: (brand: string, isLarge: boolean) => ({
        height: isLarge ? 200 : 140,
        background: gradients[brand as keyof typeof gradients] || gradients["Dermalosophy"],
        position: "relative" as const,
        overflow: "hidden",
      }),
      productInfo: {
        padding: 18,
      },
      productBrand: {
        fontSize: 10,
        fontWeight: 600,
        color: c.textMuted,
        fontFamily: FONT_MONO,
        letterSpacing: "0.08em",
        textTransform: "uppercase" as const,
        marginBottom: 6,
      },
      productName: {
        fontSize: 17,
        fontWeight: 500,
        fontFamily: FONT_HEADING,
        marginBottom: 8,
        lineHeight: 1.3,
      },
      productPrice: {
        fontSize: 18,
        fontWeight: 700,
        fontFamily: FONT_MONO,
        color: c.accent,
      },
      featuredBadge: {
        position: "absolute" as const,
        top: 14,
        [isRTL ? "right" : "left"]: 14,
        padding: "6px 12px",
        borderRadius: 12,
        backgroundColor: "rgba(255,255,255,0.95)",
        backdropFilter: "blur(8px)",
        fontSize: 10,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        color: c.accentDark,
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
      },

      // ─────────────────────────────────────────────────
      // CAROUSEL
      // ─────────────────────────────────────────────────
      carousel: {
        display: "flex",
        gap: 14,
        overflowX: "auto" as const,
        paddingBottom: 12,
        scrollbarWidth: "none" as const,
        msOverflowStyle: "none" as const,
        scrollSnapType: "x mandatory",
      },
      carouselCard: {
        minWidth: 170,
        backgroundColor: c.cardSolid,
        borderRadius: 20,
        overflow: "hidden",
        boxShadow: c.shadow,
        flexShrink: 0,
        cursor: "pointer",
        transition: "transform 0.3s ease",
        border: `1px solid ${c.border}`,
        scrollSnapAlign: "start",
      },

      // ─────────────────────────────────────────────────
      // SERVICES
      // ─────────────────────────────────────────────────
      serviceCard: (index: number) => ({
        marginBottom: 18,
        borderRadius: 24,
        overflow: "hidden",
        boxShadow: c.shadow,
        animation: `fadeIn 0.6s ease ${index * 0.15}s both`,
      }),
      serviceGradient: (gradient: string) => ({
        padding: 28,
        background: gradient,
        position: "relative" as const,
      }),
      serviceName: {
        fontSize: 24,
        fontWeight: 500,
        fontFamily: FONT_HEADING,
        color: "#1F1A16",
        marginBottom: 12,
      },
      serviceMeta: {
        display: "flex",
        gap: 16,
        marginBottom: 14,
        fontSize: 14,
        color: "rgba(31, 26, 22, 0.7)",
        fontFamily: FONT_MONO,
      },
      serviceDesc: {
        fontSize: 14,
        lineHeight: 1.6,
        color: "rgba(31, 26, 22, 0.8)",
        fontFamily: FONT_BODY,
        marginBottom: 20,
      },
      bookBtn: {
        padding: "14px 28px",
        borderRadius: 20,
        backgroundColor: "rgba(31, 26, 22, 0.9)",
        color: "#FFF",
        border: "none",
        fontSize: 14,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        transition: "all 0.3s ease",
      },

      // ─────────────────────────────────────────────────
      // BRAND / ABOUT
      // ─────────────────────────────────────────────────
      brandHero: {
        padding: "48px 20px 28px",
        textAlign: "center" as const,
        background: `linear-gradient(180deg, ${c.bgSecondary} 0%, ${c.bg} 100%)`,
      },
      avatar: {
        width: 130,
        height: 130,
        margin: "0 auto 24px",
        position: "relative" as const,
      },
      avatarRing: {
        position: "absolute" as const,
        inset: -6,
        borderRadius: "50%",
        border: `2px solid ${c.accent}`,
        animation: "avatarGlow 3s ease-in-out infinite",
      },
      avatarInner: {
        width: "100%",
        height: "100%",
        borderRadius: "50%",
        overflow: "hidden",
        position: "relative" as const,
        boxShadow: c.shadowDeep,
      },
      avatarImage: {
        width: "100%",
        height: "100%",
        objectFit: "cover" as const,
      },
      avatarPlaceholder: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        height: "100%",
        background: `linear-gradient(145deg, ${c.accent} 0%, ${c.accentDark} 100%)`,
        fontSize: 48,
        fontFamily: FONT_HEADING,
        color: "#FFF",
      },
      brandName: {
        fontSize: 32,
        fontWeight: 500,
        fontFamily: FONT_HEADING,
        marginBottom: 8,
        letterSpacing: "-0.02em",
      },
      brandRole: {
        fontSize: 14,
        color: c.textMuted,
        fontFamily: FONT_BODY,
        marginBottom: 20,
      },
      brandPhilosophy: {
        fontSize: 16,
        fontStyle: "italic",
        fontFamily: FONT_HEADING,
        lineHeight: 1.7,
        color: c.textSecondary,
        maxWidth: 320,
        margin: "0 auto",
      },
      statsRow: {
        display: "flex",
        justifyContent: "center",
        gap: 40,
        marginTop: 32,
        paddingTop: 28,
        borderTop: `1px solid ${c.border}`,
      },
      stat: {
        textAlign: "center" as const,
      },
      statNumber: {
        fontSize: 28,
        fontWeight: 600,
        fontFamily: FONT_MONO,
        color: c.accent,
        marginBottom: 4,
      },
      statLabel: {
        fontSize: 12,
        color: c.textMuted,
        fontFamily: FONT_BODY,
      },
      brandCard: {
        backgroundColor: c.cardSolid,
        borderRadius: 24,
        marginBottom: 14,
        overflow: "hidden",
        boxShadow: c.shadow,
        border: `1px solid ${c.border}`,
      },
      brandCardItem: {
        padding: "20px 22px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        cursor: "pointer",
        transition: "background-color 0.2s ease",
      },
      brandCardItemContent: {
        flex: 1,
      },
      brandCardName: {
        fontSize: 16,
        fontWeight: 500,
        fontFamily: FONT_BODY,
        marginBottom: 4,
      },
      brandCardDesc: {
        fontSize: 13,
        color: c.textMuted,
        fontFamily: FONT_BODY,
      },
      brandCardItemArrow: {
        marginInlineStart: 12,
      },
      contactBtn: {
        width: "100%",
        padding: "18px",
        borderRadius: 20,
        backgroundColor: c.accent,
        color: "#FFF",
        border: "none",
        fontSize: 15,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        marginBottom: 24,
        boxShadow: `0 4px 20px ${c.accent}40`,
        transition: "all 0.3s ease",
      },
      locationInfo: {
        display: "flex",
        justifyContent: "center",
        gap: 24,
        fontSize: 13,
        color: c.textMuted,
        fontFamily: FONT_BODY,
        marginBottom: 20,
      },
      mapLinksRow: {
        display: "flex",
        justifyContent: "center",
        gap: 16,
        marginBottom: 20,
      },
      mapLinkBtn: {
        width: 52,
        height: 52,
        borderRadius: 16,
        backgroundColor: c.cardSolid,
        border: `1px solid ${c.border}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        transition: "all 0.3s ease",
        boxShadow: c.shadow,
      },
      whatsappBtn: {
        width: "100%",
        padding: "16px",
        borderRadius: 18,
        backgroundColor: "#25D366",
        color: "#FFF",
        border: "none",
        fontSize: 15,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        boxShadow: "0 4px 16px rgba(37, 211, 102, 0.3)",
        transition: "all 0.3s ease",
      },

      // ─────────────────────────────────────────────────
      // PROFILE
      // ─────────────────────────────────────────────────
      welcomeCard: {
        marginBottom: 20,
      },
      welcomeText: {
        fontSize: 14,
        color: c.textMuted,
        fontFamily: FONT_BODY,
        marginBottom: 4,
      },
      userName: {
        fontSize: 32,
        fontWeight: 500,
        fontFamily: FONT_HEADING,
        letterSpacing: "-0.02em",
      },
      loyaltyCard: {
        background: `linear-gradient(145deg, ${c.accent} 0%, ${c.accentDark} 100%)`,
        borderRadius: 24,
        padding: 28,
        marginBottom: 28,
        position: "relative" as const,
        overflow: "hidden",
        boxShadow: c.shadowGlow,
      },
      loyaltyShimmer: {
        position: "absolute" as const,
        top: 0,
        left: "-100%",
        width: "200%",
        height: "100%",
        background: "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.15) 50%, transparent 100%)",
        animation: "shimmer 3s ease-in-out infinite",
      },
      loyaltyLevel: {
        fontSize: 11,
        fontWeight: 600,
        color: "rgba(255,255,255,0.8)",
        fontFamily: FONT_MONO,
        letterSpacing: "0.1em",
        textTransform: "uppercase" as const,
        marginBottom: 8,
        display: "flex",
        alignItems: "center",
        gap: 6,
      },
      loyaltyName: {
        fontSize: 32,
        fontWeight: 500,
        fontFamily: FONT_HEADING,
        color: "#FFF",
        marginBottom: 20,
      },
      progressBar: {
        height: 6,
        backgroundColor: "rgba(255,255,255,0.2)",
        borderRadius: 3,
        overflow: "hidden",
        marginBottom: 10,
      },
      progressFill: {
        height: "100%",
        backgroundColor: "#FFF",
        borderRadius: 3,
        width: 0,
        transition: "width 1.5s cubic-bezier(0.4, 0, 0.2, 1)",
      },
      progressText: {
        fontSize: 12,
        color: "rgba(255,255,255,0.7)",
        fontFamily: FONT_BODY,
      },

      // ─────────────────────────────────────────────────
      // ORDERS ACCORDION
      // ─────────────────────────────────────────────────
      ordersSection: {
        backgroundColor: c.cardSolid,
        borderRadius: 24,
        marginBottom: 18,
        overflow: "hidden",
        boxShadow: c.shadow,
        border: `1px solid ${c.border}`,
      },
      ordersHeader: {
        padding: "22px 24px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        cursor: "pointer",
      },
      ordersTitle: {
        fontSize: 16,
        fontWeight: 500,
        fontFamily: FONT_BODY,
        display: "flex",
        alignItems: "center",
        gap: 12,
      },
      orderItem: {
        padding: "18px 24px",
        borderTop: `1px solid ${c.border}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
      },
      orderInfo: {
        display: "flex",
        flexDirection: "column" as const,
        gap: 5,
      },
      orderId: {
        fontSize: 14,
        fontWeight: 700,
        fontFamily: FONT_MONO,
      },
      orderDate: {
        fontSize: 12,
        color: c.textMuted,
        fontFamily: FONT_BODY,
      },
      orderStatus: (status: string) => ({
        padding: "7px 14px",
        borderRadius: 14,
        fontSize: 11,
        fontWeight: 700,
        fontFamily: FONT_BODY,
        backgroundColor: status === "delivered" 
          ? "rgba(34, 197, 94, 0.12)" 
          : status === "shipping" 
          ? "rgba(59, 130, 246, 0.12)" 
          : "rgba(251, 191, 36, 0.12)",
        color: status === "delivered" 
          ? "#16a34a" 
          : status === "shipping" 
          ? "#2563eb" 
          : "#d97706",
      }),

      // ─────────────────────────────────────────────────
      // FAVORITES
      // ─────────────────────────────────────────────────
      favoriteItem: {
        padding: "16px 24px",
        borderTop: `1px solid ${c.border}`,
        display: "flex",
        alignItems: "center",
        gap: 14,
      },
      favoriteImage: (brand: string) => ({
        width: 56,
        height: 56,
        borderRadius: 14,
        background: gradients[brand as keyof typeof gradients] || gradients["Dermalosophy"],
        flexShrink: 0,
      }),
      favoriteInfo: {
        flex: 1,
        minWidth: 0,
      },
      favoriteName: {
        fontSize: 14,
        fontWeight: 500,
        fontFamily: FONT_BODY,
        marginBottom: 4,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap" as const,
      },
      favoritePrice: {
        fontSize: 14,
        fontWeight: 700,
        fontFamily: FONT_MONO,
        color: c.accent,
      },
      favoriteAddBtn: {
        padding: "10px 16px",
        borderRadius: 14,
        backgroundColor: c.accent,
        color: "#FFF",
        border: "none",
        fontSize: 12,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        whiteSpace: "nowrap" as const,
        transition: "all 0.3s ease",
      },
      favoriteReminder: {
        padding: "20px 24px",
        borderTop: `1px solid ${c.border}`,
        display: "flex",
        alignItems: "center",
        gap: 14,
        backgroundColor: `${c.accent}08`,
      },
      favoriteReminderIcon: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: `${c.accent}15`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
      },
      favoriteReminderText: {
        fontSize: 13,
        color: c.textSecondary,
        fontFamily: FONT_BODY,
        lineHeight: 1.5,
      },

      // ─────────────────────────────────────────────────
      // SETTINGS
      // ─────────────────────────────────────────────────
      settingsItem: {
        backgroundColor: c.cardSolid,
        borderRadius: 20,
        padding: "18px 22px",
        marginBottom: 14,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        boxShadow: c.shadow,
        border: `1px solid ${c.border}`,
      },
      settingsLabel: {
        fontSize: 15,
        fontFamily: FONT_BODY,
        fontWeight: 500,
      },
      themeToggle: {
        display: "flex",
        gap: 8,
      },
      themeBtn: (active: boolean) => ({
        padding: "10px 16px",
        borderRadius: 14,
        backgroundColor: active ? c.accent : c.bgSecondary,
        color: active ? "#FFF" : c.text,
        border: active ? "none" : `1px solid ${c.border}`,
        cursor: "pointer",
        fontSize: 13,
        fontFamily: FONT_BODY,
        fontWeight: 500,
        transition: "all 0.3s ease",
        boxShadow: active ? `0 2px 8px ${c.accent}30` : "none",
      }),

      // ─────────────────────────────────────────────────
      // CONSENTS
      // ─────────────────────────────────────────────────
      consentsCard: {
        backgroundColor: c.cardSolid,
        borderRadius: 24,
        padding: 4,
        marginTop: 28,
        boxShadow: c.shadow,
        border: `1px solid ${c.border}`,
      },
      consentsTitle: {
        fontSize: 15,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        padding: "18px 20px 14px",
      },
      consentItem: {
        padding: "16px 20px",
        display: "flex",
        alignItems: "center",
        gap: 14,
        cursor: "pointer",
        transition: "background-color 0.2s ease",
        borderBottom: `1px solid ${c.border}`,
      },
      consentItemLast: {
        padding: "16px 20px",
        display: "flex",
        alignItems: "center",
        gap: 14,
        cursor: "pointer",
        transition: "background-color 0.2s ease",
      },
      consentCheckbox: (checked: boolean) => ({
        width: 24,
        height: 24,
        borderRadius: 8,
        backgroundColor: checked ? c.accent : "transparent",
        border: checked ? "none" : `2px solid ${c.border}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        transition: "all 0.3s ease",
      }),
      consentLabel: {
        fontSize: 14,
        fontFamily: FONT_BODY,
        color: c.textSecondary,
      },

      // ─────────────────────────────────────────────────
      // MODALS
      // ─────────────────────────────────────────────────
      modal: {
        position: "fixed" as const,
        top: 0,
        left: "50%",
        transform: "translateX(-50%)",
        width: "100%",
        maxWidth: 430,
        height: "100vh",
        backgroundColor: c.bg,
        zIndex: 200,
        overflowY: "auto" as const,
      },
      modalHeader: {
        position: "absolute" as const,
        top: 20,
        left: 20,
        right: 20,
        display: "flex",
        justifyContent: "space-between",
        zIndex: 10,
      },
      modalImage: (brand: string) => ({
        height: 340,
        background: gradients[brand as keyof typeof gradients] || gradients["Dermalosophy"],
        position: "relative" as const,
      }),
      modalContent: {
        padding: "28px 24px",
        marginTop: -20,
        backgroundColor: c.bg,
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        position: "relative" as const,
      },
      modalBrand: {
        fontSize: 11,
        fontWeight: 600,
        color: c.textMuted,
        fontFamily: FONT_MONO,
        letterSpacing: "0.08em",
        textTransform: "uppercase" as const,
        marginBottom: 8,
      },
      modalName: {
        fontSize: 28,
        fontWeight: 500,
        fontFamily: FONT_HEADING,
        marginBottom: 16,
        lineHeight: 1.2,
        letterSpacing: "-0.02em",
      },
      modalPrice: {
        display: "flex",
        alignItems: "baseline",
        gap: 12,
        marginBottom: 20,
      },
      modalPriceMain: {
        fontSize: 28,
        fontWeight: 700,
        fontFamily: FONT_MONO,
        color: c.accent,
      },
      modalPriceOld: {
        fontSize: 18,
        fontFamily: FONT_MONO,
        color: c.textMuted,
        textDecoration: "line-through",
      },
      modalDesc: {
        fontSize: 15,
        lineHeight: 1.7,
        color: c.textSecondary,
        fontFamily: FONT_BODY,
        marginBottom: 28,
      },
      ingredientPills: {
        display: "flex",
        flexWrap: "wrap" as const,
        gap: 10,
        marginBottom: 28,
      },
      ingredientPill: {
        padding: "10px 18px",
        borderRadius: 16,
        backgroundColor: c.bgSecondary,
        fontSize: 13,
        fontFamily: FONT_BODY,
        fontWeight: 500,
        color: c.text,
        border: `1px solid ${c.border}`,
      },
      recommendedBadge: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "16px 20px",
        borderRadius: 18,
        backgroundColor: `${c.accent}12`,
        border: `1px solid ${c.accent}25`,
        marginBottom: 20,
      },
      addToCartBtn: {
        position: "fixed" as const,
        bottom: 28,
        left: "50%",
        transform: "translateX(-50%)",
        width: "calc(100% - 48px)",
        maxWidth: 382,
        padding: "18px",
        borderRadius: 20,
        backgroundColor: c.accent,
        color: "#FFF",
        border: "none",
        fontSize: 16,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        boxShadow: `0 8px 32px ${c.accent}50`,
        zIndex: 10,
        transition: "all 0.3s ease",
      },

      // ─────────────────────────────────────────────────
      // CART MODAL
      // ─────────────────────────────────────────────────
      cartOverlay: {
        position: "fixed" as const,
        inset: 0,
        backgroundColor: "rgba(0,0,0,0.5)",
        zIndex: 200,
        display: "flex",
        alignItems: "flex-end",
        justifyContent: "center",
      },
      cartModal: {
        width: "100%",
        maxWidth: 430,
        maxHeight: "85vh",
        backgroundColor: c.bg,
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        display: "flex",
        flexDirection: "column" as const,
        animation: "slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)",
      },
      cartHeader: {
        padding: "20px 24px",
        borderBottom: `1px solid ${c.border}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        flexShrink: 0,
      },
      cartTitle: {
        fontSize: 20,
        fontWeight: 600,
        fontFamily: FONT_HEADING,
      },
      cartContent: {
        flex: 1,
        overflowY: "auto" as const,
        padding: "0 24px",
      },
      cartItem: {
        display: "flex",
        gap: 16,
        padding: "20px 0",
        borderBottom: `1px solid ${c.border}`,
      },
      cartItemImage: (brand: string) => ({
        width: 80,
        height: 80,
        borderRadius: 16,
        background: gradients[brand as keyof typeof gradients] || gradients["Dermalosophy"],
        flexShrink: 0,
      }),
      cartItemInfo: {
        flex: 1,
        display: "flex",
        flexDirection: "column" as const,
        justifyContent: "center",
      },
      cartItemName: {
        fontSize: 15,
        fontWeight: 500,
        fontFamily: FONT_BODY,
        marginBottom: 6,
      },
      cartItemPrice: {
        fontSize: 16,
        fontWeight: 700,
        fontFamily: FONT_MONO,
        color: c.accent,
        marginBottom: 10,
      },
      cartQuantity: {
        display: "flex",
        alignItems: "center",
        gap: 8,
      },
      cartQuantityBtn: {
        width: 32,
        height: 32,
        borderRadius: 10,
        backgroundColor: c.accent,
        border: "none",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "all 0.2s ease",
      },
      cartQuantityValue: {
        width: 32,
        textAlign: "center" as const,
        fontSize: 15,
        fontWeight: 600,
        fontFamily: FONT_MONO,
      },
      cartFooter: {
        padding: "20px 24px",
        borderTop: `1px solid ${c.border}`,
        flexShrink: 0,
      },
      cartTotalRow: {
        display: "flex",
        justifyContent: "space-between",
        marginBottom: 18,
      },
      cartTotalLabel: {
        fontSize: 16,
        fontFamily: FONT_BODY,
        color: c.textSecondary,
      },
      cartTotalValue: {
        fontSize: 24,
        fontWeight: 700,
        fontFamily: FONT_MONO,
        color: c.accent,
      },
      cartCheckoutBtn: {
        width: "100%",
        padding: "18px",
        borderRadius: 18,
        backgroundColor: c.accent,
        color: "#FFF",
        border: "none",
        fontSize: 16,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        marginBottom: 12,
        boxShadow: `0 4px 20px ${c.accent}40`,
        transition: "all 0.3s ease",
      },
      cartClearBtn: {
        width: "100%",
        padding: "14px",
        borderRadius: 14,
        backgroundColor: "transparent",
        color: c.textMuted,
        border: `1px solid ${c.border}`,
        fontSize: 14,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        marginBottom: 8,
        transition: "all 0.3s ease",
      },
      cartBackBtn: {
        width: "100%",
        padding: "14px",
        borderRadius: 14,
        backgroundColor: "transparent",
        color: c.textSecondary,
        border: "none",
        fontSize: 14,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        transition: "all 0.3s ease",
      },

      // ─────────────────────────────────────────────────
      // CHECKOUT
      // ─────────────────────────────────────────────────
      checkoutBlock: {
        backgroundColor: c.cardSolid,
        borderRadius: 20,
        padding: 20,
        marginBottom: 18,
        border: `1px solid ${c.border}`,
      },
      checkoutBlockTitle: {
        fontSize: 16,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        marginBottom: 18,
      },
      checkoutInputRow: {
        display: "flex",
        gap: 12,
        marginBottom: 12,
      },
      checkoutLabel: {
        fontSize: 12,
        fontFamily: FONT_BODY,
        color: c.textMuted,
        marginBottom: 6,
        display: "block",
      },
      checkoutInput: {
        width: "100%",
        padding: "14px 16px",
        borderRadius: 14,
        backgroundColor: c.bgSecondary,
        border: `1px solid ${c.border}`,
        fontSize: 15,
        fontFamily: FONT_BODY,
        color: c.text,
        marginBottom: 12,
        outline: "none",
        transition: "border-color 0.3s ease",
      },
      deliveryOption: (selected: boolean) => ({
        padding: "16px 18px",
        borderRadius: 16,
        backgroundColor: selected ? `${c.accent}12` : c.bgSecondary,
        border: `2px solid ${selected ? c.accent : "transparent"}`,
        marginBottom: 10,
        display: "flex",
        alignItems: "center",
        gap: 14,
        cursor: "pointer",
        transition: "all 0.3s ease",
      }),
      deliveryOptionContent: {
        flex: 1,
      },
      deliveryOptionTitle: {
        fontSize: 15,
        fontWeight: 500,
        fontFamily: FONT_BODY,
        marginBottom: 2,
      },
      deliveryOptionDesc: {
        fontSize: 12,
        color: c.textMuted,
        fontFamily: FONT_BODY,
      },
      deliveryOptionPrice: {
        fontSize: 14,
        fontWeight: 600,
        fontFamily: FONT_MONO,
        color: c.accent,
      },
      promoRow: {
        display: "flex",
        gap: 10,
      },
      promoInput: {
        flex: 1,
        padding: "14px 16px",
        borderRadius: 14,
        backgroundColor: c.bgSecondary,
        border: `1px solid ${c.border}`,
        fontSize: 14,
        fontFamily: FONT_MONO,
        color: c.text,
        outline: "none",
      },
      promoBtn: {
        padding: "14px 24px",
        borderRadius: 14,
        backgroundColor: c.accent,
        color: "#FFF",
        border: "none",
        fontSize: 14,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        transition: "all 0.3s ease",
      },
      summaryRow: {
        display: "flex",
        justifyContent: "space-between",
        marginBottom: 12,
      },
      summaryLabel: {
        fontSize: 14,
        fontFamily: FONT_BODY,
        color: c.textSecondary,
      },
      summaryValue: {
        fontSize: 14,
        fontWeight: 600,
        fontFamily: FONT_MONO,
      },
      summaryTotal: {
        display: "flex",
        justifyContent: "space-between",
        paddingTop: 14,
        borderTop: `1px solid ${c.border}`,
        marginTop: 8,
      },
      summaryTotalLabel: {
        fontSize: 18,
        fontWeight: 600,
        fontFamily: FONT_BODY,
      },
      summaryTotalValue: {
        fontSize: 24,
        fontWeight: 700,
        fontFamily: FONT_MONO,
        color: c.accent,
      },
      summaryVat: {
        fontSize: 11,
        color: c.textMuted,
        fontFamily: FONT_BODY,
        textAlign: isRTL ? "left" as const : "right" as const,
        marginTop: 6,
      },
      paymentSelect: {
        width: "100%",
        padding: "16px 18px",
        borderRadius: 16,
        backgroundColor: c.bgSecondary,
        border: `1px solid ${c.border}`,
        fontSize: 15,
        fontFamily: FONT_BODY,
        color: c.text,
        cursor: "pointer",
        appearance: "none" as const,
        backgroundImage: `url("data:image/svg+xml,%3Csvg width='16' height='16' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M7 10l5 5 5-5' stroke='%23${c.textMuted.replace("#", "")}' stroke-width='1.5' stroke-linecap='round'/%3E%3C/svg%3E")`,
        backgroundRepeat: "no-repeat",
        backgroundPosition: isRTL ? "left 16px center" : "right 16px center",
        paddingInlineEnd: 48,
      },
      termsRow: {
        display: "flex",
        alignItems: "flex-start",
        gap: 14,
        marginBottom: 110,
      },
      termsCheckbox: (checked: boolean) => ({
        width: 24,
        height: 24,
        borderRadius: 8,
        backgroundColor: checked ? c.accent : "transparent",
        border: checked ? "none" : `2px solid ${c.border}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        cursor: "pointer",
        transition: "all 0.3s ease",
        marginTop: 2,
      }),
      termsText: {
        fontSize: 13,
        fontFamily: FONT_BODY,
        color: c.textSecondary,
        lineHeight: 1.5,
      },
      proceedBtn: {
        position: "fixed" as const,
        bottom: 28,
        left: "50%",
        transform: "translateX(-50%)",
        width: "calc(100% - 48px)",
        maxWidth: 382,
        padding: "18px",
        borderRadius: 20,
        backgroundColor: c.accent,
        color: "#FFF",
        border: "none",
        fontSize: 16,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        boxShadow: `0 8px 32px ${c.accent}50`,
        zIndex: 10,
        transition: "all 0.3s ease",
      },
      proceedBtnDisabled: {
        position: "fixed" as const,
        bottom: 28,
        left: "50%",
        transform: "translateX(-50%)",
        width: "calc(100% - 48px)",
        maxWidth: 382,
        padding: "18px",
        borderRadius: 20,
        backgroundColor: c.textMuted,
        color: "#FFF",
        border: "none",
        fontSize: 16,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "not-allowed",
        opacity: 0.5,
        zIndex: 10,
      },

      // ─────────────────────────────────────────────────
      // ORDER DETAIL MODAL
      // ─────────────────────────────────────────────────
      orderDetailBlock: {
        backgroundColor: c.cardSolid,
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
        border: `1px solid ${c.border}`,
      },
      orderDetailTitle: {
        fontSize: 14,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        marginBottom: 16,
        display: "flex",
        alignItems: "center",
        gap: 10,
      },
      orderProductItem: {
        display: "flex",
        gap: 14,
        paddingBottom: 14,
        marginBottom: 14,
        borderBottom: `1px solid ${c.border}`,
      },
      orderProductItemLast: {
        display: "flex",
        gap: 14,
      },
      orderProductImage: (brand: string) => ({
        width: 56,
        height: 56,
        borderRadius: 14,
        background: gradients[brand as keyof typeof gradients] || gradients["Dermalosophy"],
        flexShrink: 0,
      }),
      orderProductInfo: {
        flex: 1,
      },
      orderProductName: {
        fontSize: 14,
        fontWeight: 500,
        fontFamily: FONT_BODY,
        marginBottom: 4,
      },
      orderProductMeta: {
        fontSize: 12,
        color: c.textMuted,
        fontFamily: FONT_BODY,
      },
      orderProductPrice: {
        fontSize: 14,
        fontWeight: 700,
        fontFamily: FONT_MONO,
        color: c.accent,
        alignSelf: "center",
      },
      trackingBlock: {
        backgroundColor: `${c.accent}08`,
        borderRadius: 16,
        padding: 18,
        marginTop: 12,
      },
      trackingLabel: {
        fontSize: 11,
        fontWeight: 600,
        color: c.textMuted,
        fontFamily: FONT_MONO,
        letterSpacing: "0.05em",
        textTransform: "uppercase" as const,
        marginBottom: 8,
      },
      trackingNumber: {
        fontSize: 18,
        fontWeight: 700,
        fontFamily: FONT_MONO,
        color: c.text,
        marginBottom: 4,
      },
      trackingHint: {
        fontSize: 11,
        color: c.textMuted,
        fontFamily: FONT_BODY,
      },
      copyBtn: {
        padding: "10px 18px",
        borderRadius: 12,
        backgroundColor: c.accent,
        color: "#FFF",
        border: "none",
        fontSize: 13,
        fontWeight: 600,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        gap: 8,
        marginTop: 12,
        transition: "all 0.3s ease",
      },
      invoiceBtn: {
        width: "100%",
        padding: "16px",
        borderRadius: 16,
        backgroundColor: c.bgSecondary,
        color: c.text,
        border: `1px solid ${c.border}`,
        fontSize: 14,
        fontWeight: 500,
        fontFamily: FONT_BODY,
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        marginTop: 16,
        transition: "all 0.3s ease",
      },

      // ─────────────────────────────────────────────────
      // UTILITIES
      // ─────────────────────────────────────────────────
      colors: c,
      isRTL,
      theme,
      categoryLabels,
      gradients,
    };
  }, [theme, c, isRTL, animateIn, gradients]);
}
