"use client";

import { useMemo } from "react";
import type { Theme, Lang } from "../types";
import { tokens, brandGradients, FONT_HEADING, FONT_BODY, FONT_MONO } from "../theme";

export function useStyles(theme: Theme, lang: Lang, animateIn: boolean = true) {
  const c = tokens[theme];
  const isRTL = lang === "he";

  return useMemo(() => ({
    app: {
      fontFamily: `${FONT_HEADING}, ${FONT_BODY}`,
      maxWidth: 430,
      margin: "0 auto",
      height: "100vh",
      backgroundColor: c.bg,
      color: c.text,
      direction: isRTL ? "rtl" : "ltr",
      position: "relative" as const,
      overflow: "hidden",
      transition: "background-color 0.6s cubic-bezier(0.4, 0, 0.2, 1), color 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
    },
    header: {
      position: "fixed" as const,
      top: 0,
      left: "50%",
      transform: "translateX(-50%)",
      width: "100%",
      maxWidth: 430,
      height: 64,
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "0 20px",
      backgroundColor: c.glass,
      backdropFilter: "blur(24px) saturate(180%)",
      WebkitBackdropFilter: "blur(24px) saturate(180%)",
      borderBottom: `1px solid ${c.border}`,
      zIndex: 100,
      transition: "background-color 0.6s ease",
    },
    logo: {
      width: 42,
      height: 42,
      borderRadius: 21,
      border: `2px solid ${c.accent}`,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    logoPlaceholder: {
      fontFamily: FONT_HEADING,
      fontSize: 22,
      fontWeight: 500,
      color: c.accent,
      lineHeight: 1,
    },
    headerActions: {
      display: "flex",
      alignItems: "center",
      gap: 8,
    },
    iconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
      border: "none",
      cursor: "pointer",
      color: c.text,
      transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    },
    langToggle: {
      fontSize: 13,
      fontWeight: 600,
      padding: "8px 14px",
      borderRadius: 20,
      backgroundColor: c.bgSecondary,
      border: `1px solid ${c.border}`,
      cursor: "pointer",
      color: c.text,
      fontFamily: FONT_MONO,
      letterSpacing: "0.02em",
      transition: "all 0.3s ease",
    },
    cartBadge: {
      position: "absolute" as const,
      top: 6,
      [isRTL ? "left" : "right"]: 6,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: c.accent,
      color: "#FFF",
      fontSize: 10,
      fontWeight: 700,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontFamily: FONT_MONO,
      boxShadow: `0 2px 8px ${c.accent}40`,
    },
    main: {
      height: "100vh",
      overflowY: "auto" as const,
      paddingTop: 64,
      paddingBottom: 100,
    },
    nav: {
      position: "fixed" as const,
      bottom: 20,
      left: "50%",
      transform: "translateX(-50%)",
      display: "flex",
      alignItems: "center",
      gap: 4,
      padding: "8px 12px",
      backgroundColor: theme === "light" ? "rgba(255, 255, 255, 0.96)" : "rgba(31, 28, 25, 0.96)",
      backdropFilter: "blur(24px) saturate(180%)",
      WebkitBackdropFilter: "blur(24px) saturate(180%)",
      borderRadius: 20,
      border: `1px solid ${c.borderStrong}`,
      boxShadow: c.shadowDeep,
      zIndex: 100,
    },
    navItem: (active: boolean) => ({
      height: 54,
      borderRadius: 16,
      display: "flex",
      flexDirection: "column" as const,
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      padding: "6px 12px",
      backgroundColor: active ? c.accent : "transparent",
      border: "none",
      opacity: active ? 1 : 0.85,
      cursor: "pointer",
      color: active ? "#FFF" : c.textSecondary,
      transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
      fontFamily: FONT_BODY,
      fontSize: 10,
      fontWeight: 500,
      boxShadow: active ? `0 4px 16px ${c.accent}40` : "none",
      minWidth: 56,
    }),
    section: {
      padding: "28px 20px",
      opacity: animateIn ? 1 : 0,
      transform: animateIn ? "translateY(0)" : "translateY(20px)",
      transition: "opacity 0.6s cubic-bezier(0.4, 0, 0.2, 1), transform 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
    },
    // Theme colors reference
    colors: c,
    isRTL,
    theme,
  }), [theme, c, isRTL, animateIn]);
}
